export { default as BrightnessIcon } from '@material-ui/icons/Brightness6'
export { default as InfoIcon } from '@material-ui/icons/InfoOutlined'
export { default as Layers } from '@material-ui/icons/Layers'
export { default as MenuIcon } from '@material-ui/icons/Menu'

export { CodeStatsIcon } from './CodeStats'
export { FacebookIcon } from './Facebook'
export { GitHubIcon } from './GitHub'
export { GraphIcon } from './Graph'
export { InstagramIcon } from './Instagram'
export { VKIcon } from './VK'
